import { z } from "zod";
import { StructuredToolParams, tool } from "@langchain/core/tools";
import { AI_MODELS } from "@/models/enums";
import ProofReadingAgent from "@/agents/writing/ProofreadingAgent";

/**
 * Schema for the ProofReadingAgentTool.
 * This schema defines the structure of the input required by the tool.
 */
const proofReadingAgentToolSchema: StructuredToolParams = {
	name: "proof_reading_agent",
	description:
		"Proofread a piece of content based on the instructions provided",
	schema: z.object({
		original_writing_instructions: z
			.string()
			.describe(
				"The original writing instructions given to the writer (what the writer was tasked in writing, the tone and style guidelines, etc)",
			),
		content_to_proofread: z.string().describe("The content to proofread"),
	}),
};

/**
 * Creates a ProofReadingAgentTool.
 *
 * @param model - The AI model to be used for proofreading.
 * @returns A tool function that takes input and returns a proofreading report.
 *
 * Usage:
 *
 * The tool expects an input object with the following properties:
 * - original_writing_instructions: A string describing the original writing instructions.
 * - content_to_proofread: A string containing the content that needs proofreading.
 *
 * The tool will return a proofreading report generated by the ProofReadingAgent.
 */
function createProofReadingAgentTool(model: AI_MODELS) {
	return tool(async (input: any) => {
		console.log(
			`ProofReadingAgentTool initiated with the following input: ${
				JSON.stringify(input, null, 2)
			}`,
		);
		const { original_writing_instructions, content_to_proofread } = input;

		const proofReadingAgent = new ProofReadingAgent({
			instructions: original_writing_instructions,
			content: content_to_proofread,
			model: model,
		});

		const proofReadingReport = await proofReadingAgent.run();

		return proofReadingReport;
	}, proofReadingAgentToolSchema);
}

/**
 * An instance of the ProofReadingAgentTool using the CHATGPT4O model.
 * This instance can be used directly to proofread content.
 */
const proofReadingAgentTool = createProofReadingAgentTool(AI_MODELS.CHATGPT4O);

export { createProofReadingAgentTool, proofReadingAgentTool };
